name: Update README with NPM version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README with NPM version
        run: |
          npm install -g npm
          VERSION=$(npm info react-use-observe-changes version)
          sed -i "s/\[!\[npm version\].*]/\[!\[npm version](https:\/\/badge.fury.io\/js\/react-use-observe-changes.svg)](https:\/\/www.npmjs.com\/package\/react-use-observe-changes)/" README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with NPM version $VERSION"
          git push